name: Create Major Release Version Branch

on: workflow_dispatch

run-name: Create new version for upcoming major release

jobs:
  check-outdated-dependencies:
    name: Check Outdated Dependencies
    uses: valkyrjaio/.github/.github/workflows/_check-outdated-php-dependencies.yml@9b108a21f1a7161aef43c83046266f2c8de60165
    secrets: inherit
    with:
      php-version: '8.4'
      dependencies: |
        [
          {"name": "Root Packages", "command": "root-outdated-check-major-release"},
          {"name": "PHPStan", "command": "phpstan-outdated-check-major-release"}
        ]

  get-version:
    needs: check-outdated-dependencies
    uses: valkyrjaio/.github/.github/workflows/_get-version.yml@9b108a21f1a7161aef43c83046266f2c8de60165
    secrets: inherit

  create:
    needs: get-version
    uses: valkyrjaio/.github/.github/workflows/_create-version-branch.yml@9b108a21f1a7161aef43c83046266f2c8de60165
    secrets: inherit
    with:
      version: ${{ needs.get-version.outputs.version }}
      branch: ${{ needs.get-version.outputs.branch }}
